# Blueprint to create web service on render
services:
  - name: portfolio-nuxt
    type: web
    plan: free
    runtime: image
    previews:
      generation: automatic
    region: frankfurt
    domains:
      - dossouyannick.com
    image:
      url: ghcr.io/hurricaane/portfolio-nuxt:main
    envVars:
      - fromGroup: portfolio-nuxt-env
